# Generated by Django 2.1.7 on 2019-03-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msuhotlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHowTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('howto_url', models.URLField()),
                ('howto_description', models.TextField(max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msuhotlib.Person')),
            ],
            options={
                'db_table': 'Admin HowTO Uploads',
            },
        ),
    ]
