# Generated by Django 2.1.7 on 2019-03-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msuhotlib', '0002_adminhowto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminHowTo',
            new_name='AdminHowToLink',
        ),
    ]
